### ISSUE TITLE
Hi,friend!!

### ISSUE THREAD

**Issue by 74284853** [OneOneLiu/ggcnn_cornell_dataset#1]
Could I ask you one question?What is the address where you download this cornell dataset?I can't log on to the previous website.

**Comment by OneOneLiu** [comment]
Hi,I found the link is invalid ,too. but luckily,I downloaded it to my computer before,however, I have no idea how people share files in other countries(other than China),so ,I think I can just send it to you as email attachments.Here is the first 5 files(the maximum size of the attachment is 3GB),if this method works,tell me and I will send you another 5 files,if it fails, you can tell me which way you usually use to share big files,I would like to try.
从QQ邮箱发来的超大附件

01.zip (541.22M, 2021年02月08日 08:53 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f633831fa5815ee3deab17743340b1f0752010653555d551950090557190d000051155051040e1d57565952560d0c5505540c5265323900054d4258153404&t=exs_ftn_download&code=4c81e490




02.zip (550.29M, 2021年02月08日 09:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=096339392159f8eb3beab07f4239511903055c0b5501520f1f5401015d1457535456145b565c531b05530f0b520d01050a515b0c643f6306004d435014395e&code=2c99d9c6




03.zip (555.25M, 2021年02月08日 09:28 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5f393431e8ce7ceb6db0bd771e300519555b04065a030204490b0d500e1d0305075d19500055521b5c5d0d0300000e015d0a00023836370657174e5848300a&t=exs_ftn_download&code=d9418076




04.zip (555.13M, 2021年02月08日 09:41 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=583831667c837fec6ab1b8201063001e505a505f030106064e0a03530f4e0606070e1c5f5754511c545b030203060107540057023665320157164b0f46630f&t=exs_ftn_download&code=c81f6c21




05.zip (555.57M, 2021年02月08日 09:46 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5e306533b9eb22ea6cb9ec75403356185005540357510106480357525e1e50525c56480b0702511a52015707510007565d03525566356407501e1f5a163359&t=exs_ftn_download&code=e0e3f3d7

**Comment by OneOneLiu** [comment]
Hi, I found the link is invalid, too. but luckily, I downloaded it to my computer before, however, I have no idea how people share files in other countries(other than China), so, I wonder whether I can just send it to you as email attachments. If you need it, just leave your email address here, by the way, if you have some better ways to share files, tell me and I would like to try.

**Comment by 74284853** [comment]
Thank you very much!I have successfully received your dataset file,But only one is normal,I'm trying to find new ways to transfer files,Excuse me?Are you Chinese?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OneOneLiu/ggcnn_cornell_dataset"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月9日(星期六) 上午10:40
收件人:&nbsp;"OneOneLiu/ggcnn_cornell_dataset"<ggcnn_cornell_dataset@noreply.github.com&gt;;
抄送:&nbsp;"三亚及其周边酋长国国王"<1912741882@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OneOneLiu/ggcnn_cornell_dataset] Hi,friend!! (#1)





 Hi,I found the link is invalid ,too. but luckily,I downloaded it to my computer before,however, I have no idea how people share files in other countries(other than China),so ,I think I can just send it to you as email attachments.Here is the first 5 files(the maximum size of the attachment is 3GB),if this method works,tell me and I will send you another 5 files,if it fails, you can tell me which way you usually use to share big files,I would like to try. 
 从QQ邮箱发来的超大附件 
  
 01.zip (541.22M, 2021年02月08日 08:53 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f633831fa5815ee3deab17743340b1f0752010653555d551950090557190d000051155051040e1d57565952560d0c5505540c5265323900054d4258153404&amp;t=exs_ftn_download&amp;code=4c81e490 
  
  
  
  
 02.zip (550.29M, 2021年02月08日 09:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=096339392159f8eb3beab07f4239511903055c0b5501520f1f5401015d1457535456145b565c531b05530f0b520d01050a515b0c643f6306004d435014395e&amp;code=2c99d9c6 
  
  
  
  
 03.zip (555.25M, 2021年02月08日 09:28 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5f393431e8ce7ceb6db0bd771e300519555b04065a030204490b0d500e1d0305075d19500055521b5c5d0d0300000e015d0a00023836370657174e5848300a&amp;t=exs_ftn_download&amp;code=d9418076 
  
  
  
  
 04.zip (555.13M, 2021年02月08日 09:41 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=583831667c837fec6ab1b8201063001e505a505f030106064e0a03530f4e0606070e1c5f5754511c545b030203060107540057023665320157164b0f46630f&amp;t=exs_ftn_download&amp;code=c81f6c21 
  
  
  
  
 05.zip (555.57M, 2021年02月08日 09:46 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5e306533b9eb22ea6cb9ec75403356185005540357510106480357525e1e50525c56480b0702511a52015707510007565d03525566356407501e1f5a163359&amp;t=exs_ftn_download&amp;code=e0e3f3d7

**Comment by 74284853** [comment]
打扰您了，我是这方面的新手想向您咨询一下抓取点识别相关论文中在数据集上的测试精度（accuracy）是怎么计算的？希望您有时间可以回复一下，谢谢！

**Comment by 74284853** [comment]
Hi,friend.I'm new to this field.I read this paper and tried to reproduce it,but meet some problems,Could you tell me how to calculation speed of single image use'eval_ggcnn'?Just like the '6ms for a single depth image' presented in the paper.

**Comment by OneOneLiu** [comment]
I think the

>  "the GG-CNN takes 6 ms to compute for a single depth image" 

means the time for GGCNN to calculate the loss when the input is  one single depth image(`batch_size=1`,`use-depth=True`,`use-rgb=False`) ,and I believe the corresponding line in the code is :
```python
# line 78 in eval_ggcnn.py
lossd = net.compute_loss(xc, yc)
```
You can simply add `time.time()` before and after the line to get the current time, then you can get the speed of the line by making a simple subtraction.
```python
time_start = time.time()
lossd = net.compute_loss(xc, yc)
time_end = time.time()

speed = time_end-time_start
```

**Comment by OneOneLiu** [comment]
> Hi,friend.I'm new to this field.I read this paper and tried to reproduce it,but meet some problems,Could you tell me how to calculation speed of single image use'eval_ggcnn'?Just like the '6ms for a single depth image' presented in the paper.

I think the

>  "the GG-CNN takes 6 ms to compute for a single depth image" 

means the time for GGCNN to calculate the loss when the input is  one single depth image(`batch_size=1`,`use-depth=True`,`use-rgb=False`) ,and I believe the corresponding line in the code is :
```python
# line 78 in eval_ggcnn.py
lossd = net.compute_loss(xc, yc)
```
You can simply add `time.time()` before and after the line to get the current time, then you can get the speed of the line by making a simple subtraction.
```python
time_start = time.time()
lossd = net.compute_loss(xc, yc)
time_end = time.time()

speed = time_end-time_start
```

**Comment by OneOneLiu** [comment]
> Thank you very much!I have successfully received your dataset file,But only one is normal,I'm trying to find new ways to transfer files,Excuse me?Are you Chinese?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "OneOneLiu/ggcnn_cornell_dataset" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月9日(星期六) 上午10:40 收件人:&nbsp;"OneOneLiu/ggcnn_cornell_dataset"<ggcnn_cornell_dataset@noreply.github.com&gt;; 抄送:&nbsp;"三亚及其周边酋长国国王"<1912741882@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [OneOneLiu/ggcnn_cornell_dataset] Hi,friend!! (#1) Hi,I found the link is invalid ,too. but luckily,I downloaded it to my computer before,however, I have no idea how people share files in other countries(other than China),so ,I think I can just send it to you as email attachments.Here is the first 5 files(the maximum size of the attachment is 3GB),if this method works,tell me and I will send you another 5 files,if it fails, you can tell me which way you usually use to share big files,I would like to try. 从QQ邮箱发来的超大附件 01.zip (541.22M, 2021年02月08日 08:53 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f633831fa5815ee3deab17743340b1f0752010653555d551950090557190d000051155051040e1d57565952560d0c5505540c5265323900054d4258153404&amp;t=exs_ftn_download&amp;code=4c81e490 02.zip (550.29M, 2021年02月08日 09:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=096339392159f8eb3beab07f4239511903055c0b5501520f1f5401015d1457535456145b565c531b05530f0b520d01050a515b0c643f6306004d435014395e&amp;code=2c99d9c6 03.zip (555.25M, 2021年02月08日 09:28 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5f393431e8ce7ceb6db0bd771e300519555b04065a030204490b0d500e1d0305075d19500055521b5c5d0d0300000e015d0a00023836370657174e5848300a&amp;t=exs_ftn_download&amp;code=d9418076 04.zip (555.13M, 2021年02月08日 09:41 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=583831667c837fec6ab1b8201063001e505a505f030106064e0a03530f4e0606070e1c5f5754511c545b030203060107540057023665320157164b0f46630f&amp;t=exs_ftn_download&amp;code=c81f6c21 05.zip (555.57M, 2021年02月08日 09:46 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5e306533b9eb22ea6cb9ec75403356185005540357510106480357525e1e50525c56480b0702511a52015707510007565d03525566356407501e1f5a163359&amp;t=exs_ftn_download&amp;code=e0e3f3d7 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I'm Chinese.

**Comment by 74284853** [comment]
可以加一下您的微信吗？我想进一步和您进行学术的探讨？我的微信号是18789371622^_^

发自我的&nbsp;iPad


------------------ Original ------------------

**Comment by 74284853** [comment]
> > 嗨，朋友。我是该领域的新手。我阅读了本文并尝试进行复制，但是遇到了一些问题，能否告诉我如何使用'eval_ggcnn'计算单个图像的速度？就像'6ms for a本文中介绍的“单深度图像”。
> 
> 我觉得
> 
> > “ GG-CNN需要6毫秒来计算单个深度图像”
> 
> 装置的时间GGCNN来计算损失当输入是一个单个深度图像（`batch_size=1`，`use-depth=True`，`use-rgb=False`），并且相信在代码对应的行是：
> 
> ```python
> ＃eval_ggcnn.py中的第78行
> lossed  =  net。compute_loss（xc，yc）
> ```
> 
> 您可以简单地`time.time()`在行之前和之后添加以获取当前时间，然后可以通过进行简单的减法来获得行的速度。
> 
> ```python
> time_start  = 时间。时间（）
> 损失 = 净值。compute_loss（xc，yc）
>  time_end  = 时间。时间（）
> 
> 速度 =  time_end - time_start
> ```
I add the same code here, but I can't get the speed in the author's paper(6ms), which is about 1.3ms on my computer.I use the gpu with 2080super and cuda10.

**Comment by OneOneLiu** [comment]
恕我直言，，这种问题还需要问吗？你这个显卡比作者的好，速度当然要快些了，不是所有指标都要达到跟作者一模一样的。
