### ISSUE TITLE
您好，我想请问一下，做测试的时候，如何将640*480的深度图处理，转为网络的输入（原文中300*300）

### ISSUE THREAD

**Issue by bestgodok** [OneOneLiu/ggcnn_cornell_dataset#3]

**Comment by OneOneLiu** [comment]
Image这个类里面是有裁剪函数的，可以根据你输入的output_size来裁剪输入图片，想详细了解的话可以看一下我的notebook，应该是输入输出数据流这一章节里面，或者直接看image_pro. py里面的Image类也行

**Comment by bestgodok** [comment]
非常感谢！！！

**Comment by bestgodok** [comment]
> Image这个类里面是有裁剪函数的，可以根据你输入的output_size来裁剪输入图片，想详细了解的话可以看一下我的notebook，应该是输入输出数据流这一章节里面，或者直接看image_pro. py里面的Image类也行

大佬我想问一下，我现在相机用的是realsense D435i，保存深度图像的时候，可以直接保存为tiff格式吗？还是说保存为png格式然后再手动转为深度图像？

**Comment by OneOneLiu** [comment]
我没用过你这个相机，不过我觉得直接存为tiff应该没毛病，你可以试一下，有什么问题的话可以发个导出的tiff来我瞅瞅。

**Comment by bestgodok** [comment]
> 我没用过你这个相机，不过我觉得直接存为tiff应该没毛病，你可以试一下，有什么问题的话可以发个导出的tiff来我瞅瞅。

方便加个扣扣不 我传给你（1176457969）

**Comment by bestgodok** [comment]
> 我没用过你这个相机，不过我觉得直接存为tiff应该没毛病，你可以试一下，有什么问题的话可以发个导出的tiff来我瞅瞅。
大佬我能用一下您训练的模型吗？我这边测试的时候发现，深度图像有一道从左上角至右下角的一道分割线，可以很明显的看到上半部分是黑的 ，您有遇到过这种情况吗？
