### ISSUE TITLE
jacquard dataset数据集

### ISSUE THREAD

**Issue by scq6688** [OneOneLiu/ggcnn_cornell_dataset#8]

**Comment by OneOneLiu** [comment]
这个下载链接必须要你发邮件申请，对方给注册一个账户之后才能登录下载，你发了邮件之后可以稍微等几天，我记得当时也是等了挺久才收到回复的，另外最好用教育邮箱发邮件，否则可能不回复

**Comment by scq6688** [comment]
好的，谢谢前辈，可以加您个好友吗？希望您可以留言个联系方式，或者加我的手机号同微信：18862013809  QQ：3220165630。

**Comment by scq6688** [comment]
> 前辈您好，论文里的Jacquard 抓取数据集，我按照要求做了，也发了邮件，没回应，搞不到这个数据集。看到您在代码中提到您已经下载了。希望您可以将数据集的下载链接发给我一份。如果不方便发下载链接的话，您可以将这个数据集的一部分传到百度网盘里吗？或者将这个数据集的一部分通过QQ（[3220165630@qq.com](mailto:3220165630@qq.com))发给我。谢谢前辈。
